blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://discord.gg/SkVK3bxWCq
    about: Please ask and answer questions here
  - name: List a token
    url: https://github.com/mistswapdex/default-token-list#adding-a-token
    about: Any requests to add a token to MistSwap should go here
